### ISSUE TITLE
Cannot export vector map

### ISSUE THREAD

**Issue by ROS-lover** [autocore-ai/MapToolbox#10]
Hi,
I have imported my .pcd map and created the proper lanes and white lines but upping saving and exporting the csv files, this error was thrown:

![image](https://user-images.githubusercontent.com/51894258/60071845-6138ff00-96d0-11e9-9c31-8b75e561f9a2.png)

What can be the problem? Deleting a created node?

**Comment by MoeLang** [comment]
@ROS-lover  I noticed this problem, same as #8 . It seems something wrong on a WhiteLine.
I guess there might some whiteline have been deleted during your works. 
If this happened, 
1. Save your scene and project
2. Reload your scene file or relaunch unity editor
and this problem can be solved.
