### ISSUE TITLE
4 Way ruless

### ISSUE THREAD

**Issue by ROS-lover** [autocore-ai/MapToolbox#12]
Hi,

I actually got to work with the tools you guys developed. It turned out to be very helpful. I can create nodes and lane for straight road but I am not sure how to create it for 4 ways.  I tried many ways but I could not get op_planner in autoware to work with the vector map I created at 3 or 4 ways cross sections. 

i.e. can a lane that ends at a 4 way cross section, be connected by 3 more lanes? going straight, left and right? otherwise without having to allocate another lane for each way, what are the possible way to hand this situation?

![4way](https://user-images.githubusercontent.com/51894258/60782133-4b790000-a0fa-11e9-916c-a254fa56233a.PNG)

Thanks!

**Comment by MoeLang** [comment]
@ROS-lover It works well with a lane connected with 4 lanes. Make sure 4 lane both auto connected to target lane end point in editor, you can feel the start point jump to target end point if they nearby enough.
![QQ截图20190708062243](https://user-images.githubusercontent.com/7805397/60787415-4d8b9f00-a18c-11e9-8d6a-e6130cc59006.jpg)
![微信图片_20190708062050](https://user-images.githubusercontent.com/7805397/60787425-52505300-a18c-11e9-89d3-2094d80e51b7.jpg)

**Comment by ROS-lover** [comment]
Hi @MoeLang Thanks for the reply, I tried it and it works! But I do get a strange shape of lanes they look horizontally not leveled. (image bellow)
![image](https://user-images.githubusercontent.com/51894258/61505230-ea231d80-a992-11e9-8d4a-61db57137bc2.png)
My .pcd which is binarized already, is simply a smooth surface but this is what I get... I am not sure if it effects the planner's performance.
Thanks again!

**Comment by MoeLang** [comment]
@ROS-lover All lines stay close to road surface, you can view road surface by click pcd in hierarchy window, looks like a green grid mesh.
Open planner in autoware not care much about line height, but for other use make sure points map surface flat:)
![image](https://user-images.githubusercontent.com/7805397/61505721-598c2200-aa12-11e9-9c17-36790220b07b.png)

**Comment by ROS-lover** [comment]
@MoeLang  Thanks for the quick response, looks like my map's surface is not that flat. Do you happen to know how to smooth a surface of a pointcloud map we import? Thanks!

**Comment by aicarmark** [comment]
@ROS-lover what tool you are using to build map?

**Comment by ROS-lover** [comment]
@aicarmark  I am using NDT_mapping in Autoware.

**Comment by MoeLang** [comment]
@ROS-lover ndt localizer relay on correct imu data and high quality lidar data, otherwise custom modifies are needed.

**Comment by lihai88** [comment]
> @ROS-lover It works well with a lane connected with 4 lanes. Make sure 4 lane both auto connected to target lane end point in editor, you can feel the start point jump to target end point if they nearby enough.
> ![QQ截图20190708062243](https://user-images.githubusercontent.com/7805397/60787415-4d8b9f00-a18c-11e9-8d6a-e6130cc59006.jpg)
> ![微信图片_20190708062050](https://user-images.githubusercontent.com/7805397/60787425-52505300-a18c-11e9-89d3-2094d80e51b7.jpg)

please tell me how to set auto connect function,i can not find the setting.thanks.

**Comment by lihai88** [comment]
It works well with a lane connected with 4 lanes. Make sure 4 lane both auto connected to target lane end point in editor, you can feel the start point jump to target end point if they nearby enough.

@MoeLang  please tell me how to set auto connect function,i can not find the setting.thanks.
