### ISSUE TITLE
Documentation on vector map format

### ISSUE THREAD

**Issue by monkeykane** [autocore-ai/MapToolbox#13]
Hi MoeLang,

Many thanks for your tool to create vector map.
And I would like to know is there any documentation on vector map format? We want to convert vector map into opendrive format in our project.

**Comment by MoeLang** [comment]
@monkeykane Unfortunately we also have no documentation.
In fact [Vector map msg](https://gitlab.com/autowarefoundation/autoware.ai/messages/tree/master/vector_map_msgs/msg) is very easy and like Relational database, you can get informations by id in target tables.
