### ISSUE TITLE
Error while Compiling (Unity 2019.1)

### ISSUE THREAD

**Issue by repa1030** [autocore-ai/MapToolbox#15]
Hello,

I receive this error while adding Map Toolbox:

`Library\PackageCache\com.unity.burst@1.0.0\Editor\BurstAotCompiler.cs(633,32): error CS7036: There is no argument given that corresponds to the required formal parameter 'exceptionType' of 'BuildReport.AddMessage(LogType, string, string)'`

Edit: The creating of the Vector Maps is working anyway. But if i try to import it to Autoware, it shows the Error message

`terminate called after throwing an instance of 'std::invalid_argument'
what(): stoi`

Thank you for your help

**Comment by MoeLang** [comment]
@repa1030 Can you share me the scene file (named by *.unity) ? BrustAotCompiler error fixed in v0.0.9

**Comment by repa1030** [comment]
Thank you for your answer.
Here is the Scene File and the Vector Maps Data:
[VectorMaps_and_SceneFile.zip](https://github.com/autocore-ai/MapToolbox/files/3528599/VectorMaps_and_SceneFile.zip)

**Comment by MoeLang** [comment]
@repa1030 
I found '.' replaced by ','  but can not found the cause...
Right file was exported by v0.0.9 and loaded successfully.
![image](https://user-images.githubusercontent.com/7805397/63492917-044d9f80-c4ed-11e9-8b6e-88bc918d1b20.png)
![image](https://user-images.githubusercontent.com/7805397/63493260-c8ffa080-c4ed-11e9-8317-a710ef64c134.png)

**Comment by repa1030** [comment]
Everything works fine now. Thank you 👍
