### ISSUE TITLE
Load PCD with error message: Mesh 'points': abnormal mesh bounds

### ISSUE THREAD

**Issue by CyanChiu** [autocore-ai/MapToolbox#16]
Dear Sir,
I have a PCD file in FIELDS x y z intensity binary format as attached.
[road_pcd.zip](https://github.com/autocore-ai/MapToolbox/files/3594926/road_pcd.zip)
This pcd file can be used by open planner. But when I  load this PCD file in unity, I got the error as below:
```
Mesh 'points': abnormal mesh bounds - most likely it has some invalid vertices (+/-inifinity or NANs) due to errors exporting.
Mesh bounds min=(-inf, -inf, -inf), max=(inf, inf, inf). Please make sure the mesh is exported without any errors.
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

```
But I don't know if my file has any wrong format for this plugging tool, could you help me to check? Thanks

**Comment by MoeLang** [comment]
@CyanChiu  This plugin support pcd format :
**FIELDS x y z intensity
SIZE 4 4 4 4
TYPE F F F F**

but this file in format :
**FIELDS x y z intensity
SIZE 4 4 4 1
TYPE F F F U**

**Comment by CyanChiu** [comment]
Oh! I just checked the FIELDS and missed the data type of intensity. Thanks for your remind, I will transform this file and check again.
