### ISSUE TITLE
which frame does this tool use?

### ISSUE THREAD

**Issue by liuyf5231** [autocore-ai/MapToolbox#17]
Hi MoeLang,
which frame does this tool use?
autoware vectormap Bx Ly means northing and easting. So i want to know which frame does points map  use?

**Comment by MoeLang** [comment]
Hello @liuyf5231 
This tool place all points map and vector map in world space, equals "map frame" in autoware.
![image](https://user-images.githubusercontent.com/7805397/65202740-2ff88100-dabd-11e9-828b-d8c4c45427a2.png)
In this tool, axis X means south and Z means east.

**Comment by liuyf5231** [comment]
ok thanks
