### ISSUE TITLE
How to generate the pcd map?

### ISSUE THREAD

**Issue by daohu527** [autocore-ai/MapToolbox#18]
How to make a pcd map, I found that autoware provides a map service, it seems to be charging now. [link](https://tools.tier4.jp/feature/point_cloud_map_builder/)

**Comment by RomanDmowski** [comment]
Here you can find an Autoware Manual:
https://github.com/CPFL/Autoware-Manuals/blob/master/en/Autoware_TierIV_Academy_v1.1.pdf

Look into Chapter 2 - 3D Map Generation

**Comment by daohu527** [comment]
thanks a lot, I will read it then.
