### ISSUE TITLE
global path planning

### ISSUE THREAD

**Issue by trustmetao** [autocore-ai/MapToolbox#21]
Given the end point with the vector drawn by Unity, can't we plan a suitable path based on multiple feasible paths?

![unity](https://user-images.githubusercontent.com/52956223/70906879-67d27e80-2042-11ea-8749-d033526e4ed1.png)

**Comment by MoeLang** [comment]
Hello @trustmetao , use op_global_planner and issue #12 may help you.

**Comment by trustmetao** [comment]
Thanks for the quick response, I wanna know how to draw the traffic lights in your vector map tools. And In my vector map, only one main road is connected and the other roads are separated. A vector map like this cannot plan a path with the open planner, right?
![unity_vector](https://user-images.githubusercontent.com/52956223/71239205-eb40e800-2340-11ea-817c-fa42c2d20db1.png)
![end_point](https://user-images.githubusercontent.com/52956223/71239214-f0059c00-2340-11ea-9c74-032e68a1b100.png)

**Comment by MoeLang** [comment]
Yes, op planner needs connected lane, green bulb of traffic lights should be attached to target stop line script, reference to issue #5.

**Comment by trustmetao** [comment]
How should I draw like this traffic lights in vector map tools? Besides, are crosswalk unnecessary in vector map?
![99145_000281](https://user-images.githubusercontent.com/52956223/71248296-7330ed00-2355-11ea-81be-d8bff5214077.jpg)

**Comment by trustmetao** [comment]
How should I draw like this traffic lights in vector map tools? Besides, are crosswalk unnecessary in vector map?
![6567](https://user-images.githubusercontent.com/52956223/71248575-200b6a00-2356-11ea-974d-9e319acd2e18.png)

**Comment by trustmetao** [comment]
And the singaldata has no height imformation, just like pole, poledate. Are height imformation of trafficlights unnecessary in this tools?

**Comment by MoeLang** [comment]
For current version of Autoware, pole is unnecessary in package trafficlight_recognizer. But I found a problem that trafficlight may not work in Autoware, and I will fix and update this tool this week.
方便的话欢迎添加个人微信“heli-heli”获取更详细帮助
