### ISSUE TITLE
Binary format pcd supported only currently !

### ISSUE THREAD

**Issue by SLAMgreen** [autocore-ai/MapToolbox#26]
Thank you for the free code for us!
I have add autoware toolkit packages into unity following the video.But when i add pcd files which is created by autoware 1.11 into an unity3d project ,i meet an error.
**
Binary format pcd supported only currently !
UnityEngine.Debug:LogError(Object)
Packages.MapToolbox.PcdTools.PcdReader:.ctor(String) (at Library/PackageCache/com.autocore.map-toolbox@b24654f78edb9b8f3fa0a230e175b1bbb695e4a2/PcdTools/PcdReader.cs:108)
Packages.MapToolbox.PcdTools.Editor.PcdImporter:OnImportAsset(AssetImportContext) (at Library/PackageCache/com.autocore.map-toolbox@b24654f78edb9b8f3fa0a230e175b1bbb695e4a2/PcdTools/Editor/PcdImporter.cs:31)
UnityEditor.AssetDatabase:Refresh()
Packages.MapToolbox.PcdTools.Editor.EditorMenuExterns:LoadPcdFolder() (at Library/PackageCache/com.autocore.map-toolbox@b24654f78edb9b8f3fa0a230e175b1bbb695e4a2/PcdTools/Editor/EditorMenuExterns.cs:43)
**

Could you please help me to solve the problem?

**Comment by MoeLang** [comment]
@SLAMgreen Current version 0.1.0 may solve your problem

**Comment by SLAMgreen** [comment]
Thx
