### ISSUE TITLE
where is the UnityOctree?

### ISSUE THREAD

**Issue by cocoa97** [autocore-ai/MapToolbox#29]
I can't load pcd，which format like this：
`# .PCD v0.7 - Point Cloud Data file format
VERSION 0.7
FIELDS x y z intensity
SIZE 4 4 4 4
TYPE F F F F
COUNT 1 1 1 1
WIDTH 603452
HEIGHT 1
VIEWPOINT 0 0 0 1 0 0 0
POINTS 603452
DATA ascii
26.502167 97.391144 -1.8180114 22
25.723701 97.498932 -1.8092144 22
25.876507 97.411179 -1.8140769 22
26.125629 97.473999 -1.815798 22
`
Thanks for your intronduction,but I could not find the UnityOctree, I would be very appreciate it if you can update it.

**Comment by MoeLang** [comment]
UnityOctree remove during update
