### ISSUE TITLE
DllNotFoundException: unity_pcl

### ISSUE THREAD

**Issue by dymons** [autocore-ai/MapToolbox#35]
Hi! When I try to upload a PCD file, I get the following error
![error](https://user-images.githubusercontent.com/20445903/86760296-ca768080-c04d-11ea-8bcd-762e644fd52a.png)

<details>
File format PCD

```
# .PCD v0.7 - Point Cloud Data file format
VERSION 0.7
FIELDS x y z intensity
SIZE 4 4 4 4
TYPE F F F F
COUNT 1 1 1 1
WIDTH 10000
HEIGHT 1
VIEWPOINT 0 0 0 1 0 0 0
POINTS 10000
DATA binary
```

</details>

I've read all the current issues, but couldn't find an answer to the solution of this error. Could you please help me to solve the problem?

**Comment by harderthan** [comment]
Hello, @dymons. Did you fix this problem?

**Comment by ROS-lover** [comment]
Has anyone find a solution for this?
