### ISSUE TITLE
I can't put one pole on the road and can't move the signal lamp

### ISSUE THREAD

**Issue by yuhang9803** [autocore-ai/MapToolbox#38]
when I tried to put one pole and several signal lamps on the road.
I found following questions:
1. I can't see one thing like pole in my scene when I clicked the "CollectionPole" button. What is the way to put one pole on a cross?
2.How can I remove the signal lamp when I add one signal? In my scene, it just remains immovatable.
looking forward to your reply!

**Comment by MoeLang** [comment]
Lamp moved by unity default move tool (keyboard W)  and pole are not supported .
