### ISSUE TITLE
how to export .csv files

### ISSUE THREAD

**Issue by yuhang9803** [autocore-ai/MapToolbox#41]
hi
when I finishing labeling the map with toolbox, how can i export the corresponding csv files ?
thank you

**Comment by MoeLang** [comment]
Click "Autoware Vector Map” script last button "Save Vector Map into folder".

**Comment by harderthan** [comment]
the red button on the "Inspector" tab

![image](https://user-images.githubusercontent.com/13160765/89246234-a060b000-d645-11ea-8333-cd3bff0bf367.png)

**Comment by idontlikelongname** [comment]
> Click "Autoware Vector Map” script last button "Save Vector Map into folder".

thanks for you awesome map tools, I meet a issue when "Save Vector Map into folder".
When I was drawing map, to avoid crash, I was used to saving during drawing. 
but I find a issue, if save many times during saving, I can only record the elements (points or lines) during the lastest saving to now. but the elements before last saving are lost !!!!

**Comment by hamlinzheng** [comment]
> > Click "Autoware Vector Map” script last button "Save Vector Map into folder".
> 
> thanks for you awesome map tools, I meet a issue when "Save Vector Map into folder".
> When I was drawing map, to avoid crash, I was used to saving during drawing.
> but I find a issue, if save many times during saving, I can only record the elements (points or lines) during the lastest saving to now. but the elements before last saving are lost !!!!

Maybe I meet the same problem, I can only save part of the data, How did you solve this problem?

**Comment by idontlikelongname** [comment]
> > > Click "Autoware Vector Map” script last button "Save Vector Map into folder".
> > 
> > 
> > thanks for you awesome map tools, I meet a issue when "Save Vector Map into folder".
> > When I was drawing map, to avoid crash, I was used to saving during drawing.
> > but I find a issue, if save many times during saving, I can only record the elements (points or lines) during the lastest saving to now. but the elements before last saving are lost !!!!
> 
> Maybe I meet the same problem, I can only save part of the data, How did you solve this problem?

close the unity editor, reopen and save again
I think its bug in editor scripts
