### ISSUE TITLE
How to  create a loop with lane

### ISSUE THREAD

**Issue by yucedagonurcan** [autocore-ai/MapToolbox#44]
Hi,

I wonder how can we create a loop with lanes? 

I am trying to stitch last lane and first lane of the GoSlicesLane

![image](https://user-images.githubusercontent.com/16342629/89976175-69575380-dc70-11ea-9db0-e1a2db4759e0.png)

But it won't snap. 

Generally I want to know how can I connect two lanes(merge) into one lane? I know other issues related to this one but you can clearly see that I need to be able to snap them.

I tried to add another lane between last lane and first lane but no luck.

Is there any documentation/tutorial for new version? 

Have a greay day.

**Comment by MoeLang** [comment]
GoSlicesLane can not connect itself by merge first and last lane.
For loop street like this, you'd better create 8 GoSlicesLane and connect them, 4 on straight and 4 on junction.
![image](https://user-images.githubusercontent.com/7805397/89977082-d7b20b00-dc9c-11ea-9859-814a891e6d75.png)

**Comment by yucedagonurcan** [comment]
Thank you for your help, resolved the issue.
