### ISSUE TITLE
How to merge two lanes at the same node 

### ISSUE THREAD

**Issue by Anderson0609** [autocore-ai/MapToolbox#45]
Excuse me, I have a doubt about the plugin :
due to the vector map format in the csv file, how to merge two lanes at the same node in the following instance. 
![无标题](https://user-images.githubusercontent.com/44046733/90239340-eb56a080-de59-11ea-81f3-11f688e922e6.png)

**Comment by MoeLang** [comment]
Only first and last node can used to merge lanes. In this instance you should drag first node of left two lanes to last node of right lane.

**Comment by Anderson0609** [comment]
Do you mean the first node of left two lanes Node 1 and Node 2, the last node of right lane Node3， as  the following picture？
but how to merge the nodes？ thank you so much.
![无标题](https://user-images.githubusercontent.com/44046733/90241685-235fe280-de5e-11ea-9f61-bf4a4b268212.png)

**Comment by MoeLang** [comment]
Yes, just drag node1 and node2 to node3, they will auto connected in short distance.
![1](https://user-images.githubusercontent.com/7805397/90245689-bbad9580-de65-11ea-9b5c-68c9214a86c0.gif)

**Comment by Anderson0609** [comment]
Thank you so much for you demo operation. but at the last step , what operation did you do to the right lane? Just click the mouse or double click ？ any other Additional operations  is needed？ thank you for your kind reply.

**Comment by Anderson0609** [comment]
I got it , thank you very much,
