### ISSUE TITLE
Why the parameters such  B,L,H in point.csv are zero 

### ISSUE THREAD

**Issue by doggyc** [autocore-ai/MapToolbox#47]
the point should have the lat and lon information,why the generated point.csv have no such information in B,L,H

**Comment by MoeLang** [comment]
B and L are not supported and H needs modify height of points (y in transform component).

**Comment by doggyc** [comment]
> B and L are not supported and H needs modify height of points (y in transform component).
thanks,and I want to know where is the origin of the generated vector map,and how the Bx,Ly are caculated.

**Comment by MoeLang** [comment]
PCD file should be placed in origin, then add vector map base on points cloud position.
So vector map origin is same as PCD origin.

**Comment by doggyc** [comment]
> PCD file should be placed in origin, then add vector map base on points cloud position.
> So vector map origin is same as PCD origin.
so point cloud maps come with latitude and longitude information?

**Comment by doggyc** [comment]
how can I set the origin in unity

**Comment by MoeLang** [comment]
Just import PCD and drag PCD into Hierarchy, make sure Transform not moved.
![image](https://user-images.githubusercontent.com/7805397/90588317-e86aff80-e20d-11ea-8141-77a4486389fe.png)

**Comment by doggyc** [comment]
> Just import PCD and drag PCD into Hierarchy, make sure Transform not moved.
> ![image](https://user-images.githubusercontent.com/7805397/90588317-e86aff80-e20d-11ea-8141-77a4486389fe.png)

thanks a lot,do you have wechat ,I want  some more details.

**Comment by MoeLang** [comment]
> thanks a lot,do you have wechat ,I want some more details.

wechat id: heli-heli
