### ISSUE TITLE
Right way to create intersections and bidirectional lanes

### ISSUE THREAD

**Issue by yucedagonurcan** [autocore-ai/MapToolbox#49]
Hello,

I want to create something like this:

![image](https://user-images.githubusercontent.com/16342629/90818732-a342ec80-e337-11ea-9cd6-d2285408a775.png)

But unfortunately open planner gives me no centerlines. I want to know what is the right way to construct this kind of intersections between lanes.

Also, can we create bidirectional lanes  in Autocore? Because if I draw two lanes with different directions close to each other, planning is not successfull.

Have a great day.

**Comment by MoeLang** [comment]
This map is similar to your scenario, please load and have a look. 
[Map.zip](https://github.com/autocore-ai/MapToolbox/files/5105864/Map.zip)

Can you drag AutowareADASMap to Project window to make a prefab ( restore by right click on AutowareADASMap and "Unpack Prefab" ) then send me the prefab, thus I can find the problem.

**Comment by yucedagonurcan** [comment]
Hello,

It is so frustrating that I drawed map from scratch for many times. Sometimes it works sometimes it doesn't like some kind of probabilistic model( bad one).

I don't see any centerlines wit op planner.

[AutowareADASMap.zip](https://github.com/autocore-ai/MapToolbox/files/5129666/AutowareADASMap.zip)

**Comment by MoeLang** [comment]
I noticed the zigzag and make this lane straight .

![image](https://user-images.githubusercontent.com/7805397/91374907-df041780-e84b-11ea-8d18-72d151f42150.png)

![image](https://user-images.githubusercontent.com/7805397/91375237-b29ccb00-e84c-11ea-9d13-63235976a92e.png)

[AutowareADASMap 1.zip](https://github.com/autocore-ai/MapToolbox/files/5133579/AutowareADASMap.1.zip)

**Comment by yucedagonurcan** [comment]
Hello,

We did this on purpose, but I found the issue without changing that zigzag:

In the intersection there are two lane slices and their end points are close to each other. 

I modified the slices so that their end points far from each other and OP makes the global planning successfully.
