### ISSUE TITLE
No Mesh Collider

### ISSUE THREAD

**Issue by alperenbayraktar** [autocore-ai/MapToolbox#55]
@MoeLang  Old version used to have a collider child object under the imported pcd file's hierarchy view but for the moment it is not present. 
.pcd in project view: (only points as child)
![a](https://user-images.githubusercontent.com/35660502/101487889-e02b0180-396f-11eb-9c9b-0a0434825a5a.png)
.pcd in hierarchy view: (no children)
![image](https://user-images.githubusercontent.com/35660502/101487991-06e93800-3970-11eb-89f2-a478720f2a70.png)

The vector map won't snap into the ground and will always have y = 0, this causes problems when you use tilted maps.

**Comment by MoeLang** [comment]
Yes, I removed this function because this make our map cracked and uneven, we also fixed pcd height to zero.

**Comment by alperenbayraktar** [comment]
Alright, but how are we supposed to draw the maps now? Because I can see that some of my pcd files have like 10m+ height difference from their start to end. And when you get a map file out, all the stuff are misplaced, like wayareas are 6m down under the ground. Should we rotate the map elements by hand? @MoeLang

**Comment by MoeLang** [comment]
Config the endpoint height of line by hand, then subdivision. Dont rotate any map elements, just modity y axis value.

**Comment by alperenbayraktar** [comment]
I see, it will be much time consuming unfortunately though. Thanks for fast answers!

**Comment by alperenbayraktar** [comment]
@MoeLang Is there a way to bring back mesh collider snapping? I'm also editing the package and it could be awesome if I could use the first version's snapping combined with the new map editor scriptings

**Comment by MoeLang** [comment]
This function in code [HeightMeshBuild](https://github.com/autocore-ai/MapToolbox/blob/0.0.7/PcdTools/HeightMeshBuild.cs) , I will add this feature back this weekend.

**Comment by alperenbayraktar** [comment]
Okay, I'll test it asap, thanks!

**Comment by ali-mehran-adastec** [comment]
> This function in c

THANKS: this would help a lot, though we can see the right and neat projection of vectors on image plane.  :)

**Comment by alperenbayraktar** [comment]
> 
> 
> This function in code [HeightMeshBuild](https://github.com/autocore-ai/MapToolbox/blob/0.0.7/PcdTools/HeightMeshBuild.cs) , I will add this feature back this weekend.

Hey @MoeLang  did you add this to any branch? I can't find it.

**Comment by alperenbayraktar** [comment]
Hey @moelang when are you going to add this?

**Comment by moelang** [comment]
> Hey @moelang when are you going to add this?

Yes its under testing, some api changed and cannot used in old methods.

**Comment by alperenbayraktar** [comment]
Alright thanks, have a nice day.

**Comment by alperenbayraktar** [comment]
@moelang I tried the commit, now the first node gets the actual height but the second one doesn't upload its height when you move it and always has the same height as the first node. will you add a dynamic height setting for it or should I? 
![image](https://user-images.githubusercontent.com/35660502/104185612-3f27de80-5426-11eb-8d19-0ff2113d5c1a.png)

**Comment by moelang** [comment]
> @moelang I tried the commit, now the first node gets the actual height but the second one doesn't upload its height when you move it and always has the same height as the first node. will you add a dynamic height setting for it or should I?
> ![image](https://user-images.githubusercontent.com/35660502/104185612-3f27de80-5426-11eb-8d19-0ff2113d5c1a.png)

Subdevision added height from pcd in last commit

**Comment by alperenbayraktar** [comment]
Now it works like a charm. Since setting height with subdivision (Adding ADASGoX), From and To go objects don't upload their heights after subdivision. If you add a lane and change the From position before subdivision, it looks like this, I've added some features myself but here's what I mean:
![image](https://user-images.githubusercontent.com/35660502/104287362-6387c780-54c7-11eb-8e6a-2a8a2aa82385.png)

**Comment by alperenbayraktar** [comment]
> 
> 
> @moelang Now it works like a charm. Since setting height with subdivision (Adding ADASGoX), From and To go objects don't upload their heights after subdivision. If you add a lane and change the From position before subdivision, it looks like this, I've added some features myself but here's what I mean:
> ![image](https://user-images.githubusercontent.com/35660502/104287362-6387c780-54c7-11eb-8e6a-2a8a2aa82385.png)

```
            float y = Utils.GetHeight(current.From);  //Snap the first one 
            current.From = new Vector3(current.From.x, y, current.From.z);
            foreach (var point in points)
            {                
                if (Vector3.Distance(current.From, point) > distance)
                {
                    Vector3 dest = current.From + (point - current.From).normalized * distance;
                    dest.y = Utils.GetHeight(dest);
                    current.To = dest;
                    var temp = current.AddAfter().GetComponent<LineSegment<T>>();
                    temp.DataCopy(current);
                    current = temp;
                    current.From = dest;
                }
            }
            y = Utils.GetHeight(current.To); //Snap the last one 
            current.To = new Vector3(current.To.x, y, current.To.z);
```

Added 4 lines to LineSegment.cs so now when subdivision is clicked, from and to heights are also set. @moelang
