### ISSUE TITLE
Lat Lon in Lanelet2

### ISSUE THREAD

**Issue by gnykumar** [autocore-ai/MapToolbox#57]
Hi Team / @MoeLang ,

I am learning and exploring a lot from this tool while utilizing vector map and lanelet2 map. Thanks for the tool.

I seen autoware lanelet loader and visualizer at [autoware lanelet2](https://gitlab.com/autowarefoundation/autoware.ai/common/-/merge_requests/28) along with [sample](https://gitlab.com/autowarefoundation/autoware.ai/common/uploads/d35f15087676de4f26a583a9ff9eb41d/autoware_mapping_example.osm) lanelet2 map. There is lat lon values in map but from the map I am generating from MapToolbox doesn't have lat lon, I can see that there is no reference to provide that while or after annotating. To use the Lanelet2 lib for path planning, lat lon would be required, If someone helps me to get lat lon from MapToolbox based annotated lanelet2 map It will be great.

Thanks in Advance 

For your information, I found another tool called assure mapping tool using which we can  add projection information but map is getting changed a lot which is again not usable.

**Comment by kuzen** [comment]
Hi!
You can refer to this pull request #63.

**Comment by gnykumar** [comment]
HI @kuzen ,

I tried your Modification for JOSM from https://github.com/GDUT-IIDCC/MapToolbox

But I am getting below error for saving the Lanelet2 map
![Uploading unity_save_error.png…]()

**Comment by kuzen** [comment]
> HI @kuzen ,
> 
> I tried your Modification for JOSM from https://github.com/GDUT-IIDCC/MapToolbox
> 
> But I am getting the below error for saving the Lanelet2 map
> 
> ![unity_save_error](https://user-images.githubusercontent.com/11634316/117951123-7a351280-b331-11eb-8918-e524872bca00.png)

Did you replace these files? And remember to restart Unity.
```
MapToolbox/Runtime/PCL/Geographic.dll
MapToolbox/Runtime/PCL/GeographicWarpper.dll
```

**Comment by gnykumar** [comment]
Hi @kuzen , Those files are already there in your repo. I will pulled it newly and tried. But it is closing the application at Runtime.
![unity_save_error_2](https://user-images.githubusercontent.com/11634316/118082929-adcc7700-b3db-11eb-9c7c-b1114a2b2c0c.png)

**Comment by kuzen** [comment]
Hi @gnykumar.
1. What coordinate system is the point in PCD (MRGS or UTM)? This modified version is suitable for pcd in MGRS coordinate. If you need to generate lanelet2 for pcd in UTM coordinates, you can modify line 113 in Node.cs.
2. Please confirm that your mgrs_code is correct.

**Comment by gnykumar** [comment]
@kuzen  Ok Thanks, I Understood. And Currently, Map is not in MRGS or UTM. It is in local coordinates. But How to get PCD Map in MGRS Coordinate system. 
Long back we tried for UTM but face an issue in floating-point precision. Where in higher values, the PCD map was getting sparsed in points in the map.

Is there is any standard way that I can add MRGS coordinate to PCD?

We uses NDT, LIOSAM, LEGO LOAM for building PCD Map.

**Comment by kuzen** [comment]
@gnykumar 
Just move the coordinate point. (x+x0, y+y0)
example (https://www.earthpoint.us/Convert.aspx):
point in UTM: 49Q 712345.12mE 2567890.34mN
point in MGRS: 49QGF12345126789034
point in PCD:  12345.12    67890.34
mgrs_code: 49QGF

**Comment by gnykumar** [comment]
Thanks @kuzen
