### ISSUE TITLE
Is there special rule when draw the lane in a corner

### ISSUE THREAD

**Issue by qiongwu1003** [autocore-ai/MapToolbox#59]
Hi, all

I want to draw a vector map like below:
![image](https://user-images.githubusercontent.com/65001214/103993968-51f5a580-51d1-11eb-8bce-046ca87567e8.png)

And I draw the lanes as below step:
![image](https://user-images.githubusercontent.com/65001214/103993859-2f638c80-51d1-11eb-9721-6674558aebff.png)

Does the operation correct?

**Comment by qiongwu1003** [comment]
Can anybody help me?
I drawed like above, but when i use the vector map in AutowareAI, the planning is not work.

**Comment by moelang** [comment]
> Can anybody help me?
> I drawed like above, but when i use the vector map in AutowareAI, the planning is not work.

Please provide the csv files.

**Comment by qiongwu1003** [comment]
Thanks for your reply.
This is the csv file.
[csv_file.zip](https://github.com/autocore-ai/MapToolbox/files/5794631/csv_file.zip)

And besides I use the master code.

**Comment by moelang** [comment]
I tested your csv files in autoware.ai 1.14 and op_global_planner works well with outputs :

```
Received Lanes137
Received Lines6
Received Points154
Received dtLanes137
Received Nodes142
Map Version 2
>> Extracting Lanes ...
>> Fix Waypoints errors ...
>> Create Missing lane connections ...
>> Link lanes and waypoints with pointers ...
>> Extract Signal data ...
>> Extract Stop lines data ...
>> Link missing branches and waypoints...
>> Link StopLines and Traffic Lights ...
>> Map loaded from data with 5 lanes
```

**Comment by qiongwu1003** [comment]
Thanks.
But I use the vector map refer to this [tutorial](https://www.lgsvlsimulator.com/docs/autoware-instructions/).
Is the vector map supports this mode?

**Comment by moelang** [comment]
This branch only tested for op_global_planner and not updated after  autoware.1.14

**Comment by qiongwu1003** [comment]
@moelang Thank you very much. No more question and close the issue.
