### ISSUE TITLE
[Question] Code Piece

### ISSUE THREAD

**Issue by alperenbayraktar** [autocore-ai/MapToolbox#60]
![image](https://user-images.githubusercontent.com/35660502/106604613-ed7bfb00-6570-11eb-896b-e411d001552c.png)
Hey @moelang, I've been editing this tool for a while now. Couldn't quite understand what this method exists for, some Map objects have it.

**Comment by moelang** [comment]
Maybe I forgot clean up those unused code, they are deprecated.

**Comment by alperenbayraktar** [comment]
Alright, thanks.
