### ISSUE TITLE
Real world coordinate system

### ISSUE THREAD

**Issue by yufeilongyuan** [autocore-ai/MapToolbox#64]
I'm in some trouble and I'm looking for help. I want to modify the map corresponding to the world coordinate system, but I don't know how to operate it. I hope to get help

**Comment by moelang** [comment]
What‘s the type if world coordinate system? To custom this tool I suggest add coordinate translate between import and export map files because unity inbuild world coordinate use single precision floating point precision, which makes it difficult to operate at faraway distances
