### ISSUE TITLE
ScriptedImporter error

### ISSUE THREAD

**Issue by alperenbayraktar** [autocore-ai/MapToolbox#68]
@moelang I've tried cloning main to Unity version 2019.4.0, 2019.4.18 and 2019.4.27 and results are the same:
![image](https://user-images.githubusercontent.com/35660502/120493408-9a517200-c3c3-11eb-99a3-c09342bb343a.png)
If you switch back to UnityEditor.Experimental.AssetImporters, other methods in classes Extern and PCDImporter fails.

**Comment by moelang** [comment]
During last update we changed unity version from 2019 to 2020.3

**Comment by alperenbayraktar** [comment]
I see, it works now. Thanks
