### ISSUE TITLE
how to import pcd file to maptoolbox

### ISSUE THREAD

**Issue by yuhang9803** [autocore-ai/MapToolbox#69]
hi , when i did as your document says to resolve the package , i found i could not import pcd file into the package, and the error will occur as the picture follows, in fact , when i want to import ,the unity could not find the pcd file in my computer
![32M8_N RO_UO614 0H%YFR4](https://user-images.githubusercontent.com/68856049/124256439-e37d1900-db5d-11eb-93ff-9011390ff776.png)
![屏幕截图 2021-07-02 174839](https://user-images.githubusercontent.com/68856049/124256444-e546dc80-db5d-11eb-991a-09fd26094c6f.png)

**Comment by RI-DH** [comment]
I have the same problem. Have you solved it.

**Comment by yuhang9803** [comment]
yeah，you need to check your version of unity&nbsp; &nbsp;it's probably because of your version is not matched&nbsp;



---Original---
From: ***@***.***&gt;
Date: Sat, Jul 10, 2021 23:56 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [autocore-ai/MapToolbox] how to import pcd file to maptoolbox (#69)




 
I have the same problem. Have you solved it.

**Comment by RI-DH** [comment]
> yeah，you need to check your version of unity&nbsp; &nbsp;it's probably because of your version is not matched&nbsp;
> […](#)
> ---Original--- From: ***@***.***&gt; Date: Sat, Jul 10, 2021 23:56 PM To: ***@***.***&gt;; Cc: ***@***.******@***.***&gt;; Subject: Re: [autocore-ai/MapToolbox] how to import pcd file to maptoolbox (#69) I have the same problem. Have you solved it. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

Thank you, my problem is solved.
