### ISSUE TITLE
Feature Request: Load Existing CSV Map

### ISSUE THREAD

**Issue by JWhitleyAStuff** [autocore-ai/MapToolbox#7]
While I appreciate what you guys are trying to build with this tool (and it's a really good idea), it is not very useful without being able to load an existing CSV/Aisan-format map. Is this feature coming soon?

**Comment by MoeLang** [comment]
Thank you for the advice, we're not going to add this feature currently.
Autoware provided [online tools](https://tools.tier4.jp/) which can edit discrete points.
We made this tool for quick use and fast iteration, map data is continuous and not the same as in exported csv files, some information removed during exporting.

**Comment by JWhitleyAStuff** [comment]
I see. Well, thanks for the info.
