### ISSUE TITLE
How to merge two lanes at the same node in lanelet2

### ISSUE THREAD

**Issue by ch1998** [autocore-ai/MapToolbox#78]
Excuse me, I have a doubt about the plugin :
due to the lanelet2 map format in the ocm file, how to merge two lanes at the same node in the following 
<img width="398" alt="提问" src="https://user-images.githubusercontent.com/37291486/153530742-e873388e-6730-4555-9f24-054aa7a2072b.png">
instance.

**Comment by moelang** [comment]
drag select points need to merge and drag one point to another

**Comment by ch1998** [comment]
Thank you , i do it!
