### ISSUE TITLE
can't export vector map

### ISSUE THREAD

**Issue by liuyf5231** [autocore-ai/MapToolbox#8]
MissingReferenceException: The object of type 'LineRenderer' has been destroyed but you are still trying to access it.
Your script should either check if it is null or you should not destroy the object.
Packages.AutowareUnityTools.VectorMapTools.Export.VectorMapExtern.GetCsvData (Packages.AutowareUnityTools.VectorMapTools.WhiteLine whiteLine, System.Collections.Generic.List`1[Packages.AutowareUnityTools.VectorMapTools.Export.CsvPoint]& csvPoints, System.Collections.Generic.List`1[Packages.AutowareUnityTools.VectorMapTools.Export.CsvLine]& csvLines, System.Collections.Generic.List`1[Packages.AutowareUnityTools.VectorMapTools.Export.CsvWhiteLine]& csvWhiteLines) (at Library/PackageCache/com.autocore.map-toolbox@014173a8ec8f680781f0c764ba639bf583d5ab8b/VectorMapTools/Export/VectorMapExtern.cs:121)
Packages.AutowareUnityTools.VectorMapTools.Export.VectorMapExporter.ExportMaps (System.String folder) (at Library/PackageCache/com.autocore.map-toolbox@014173a8ec8f680781f0c764ba639bf583d5ab8b/VectorMapTools/Export/VectorMapExporter.cs:72)
Packages.AutowareUnityTools.VectorMapTools.Editor.EditorMenuExterns.ExportVectorMap () (at Library/PackageCache/com.autocore.map-toolbox@014173a8ec8f680781f0c764ba639bf583d5ab8b/VectorMapTools/Editor/EditorMenuExterns.cs:79)

**Comment by MoeLang** [comment]
@liuyf5231 As the msg told, some "White Line"  component missing the "Line Renderer" component. Maybe some other exceptions made this, please try save and reopen your project,. "White Line" will try get “Line Renderer” when it loaded, and it may log some exceptions why "White Line" cant find "Line Renderer".
