### ISSUE TITLE
Ubuntu 20.04 import lanelet2_linux branch error

### ISSUE THREAD

**Issue by Kailthen** [autocore-ai/MapToolbox#84]
Unity Version: 2019.4.40f1c1

Asset Packages/com.autocore.map-toolbox/Way.cs has no meta file, but it's in an immutable folder. The asset will be ignored.
![image](https://user-images.githubusercontent.com/46671312/180130543-4fe87544-aa25-46a3-98fb-02c8a8bf5199.png)

**Comment by kevinsu628** [comment]
Hi, I have the same issue. Did you resolve it?

**Comment by Kailthen** [comment]
@kevinsu628 No, and I have tried a Unity 2021, got same error.

**Comment by Kailthen** [comment]
New error message when "Load package form disk ...":
Library/PackageCache/com.unity.jobs@0.8.0-preview.23/Unity.Jobs/IJobParallelForDefer.cs(77,85): error CS8377: The type 'U' must be a non-nullable value type, along with all fields at any level of nesting, in order to use it as parameter 'T' in the generic type or method 'NativeList<T>'

**Comment by Kailthen** [comment]
update  com.unity.jobs to 0.11.0-preview.5

**Comment by geun0196** [comment]
Hi Kailthen. I'm sorry about asking closed Issue.

Can I ask your Linux version??
