### ISSUE TITLE
Error adding package from git URL

### ISSUE THREAD

**Issue by mertbacaksiz** [autocore-ai/MapToolbox#89]
I'm using Unity 2019.4.0 on Windows10. I am getting an error while installing maptoolbox with git clone. Can you help?

![WhatsApp Image 2023-01-28 at 01 27 23](https://user-images.githubusercontent.com/99767958/215218897-7ca18177-0c98-48f6-969a-1a5eff82e963.jpeg)

**Comment by Tester2009** [comment]
Based on your error, it said no 'git' executable. It means you probably didn't install git software, as it is a requirement.

Visit https://www.git-scm.com/download/ to download git.

**Comment by mertbacaksiz** [comment]
Thanks.
